export const enum EnumArtist {
  id = 'master',
  name = 'Мастер',
}

export const enum EnumAlbums {
  master = 'master',
  sPetlyojNaShee = 's-petlyoj-na-shee',
  talkOfTheDevil = 'talk-of-the-devil',
  maniacParty = 'maniac-party',
  pesniMyortvyh = 'pesni-myortvyh',
  labirint = 'labirint',
  rcCars = 'rc-cars',
  klassika = 'klassika',
  zhizni33 = '33-zhizni',
  akustika = 'akustika',
  poTuStoronuSna = 'po-tu-storonu-sna',
  viii = 'viii',
}

export const enum EnumSongs {
  zaGranyu = 'za-granyu',
  plachSvireli = 'plach-svireli',
  veter = 'veter',
  naLiniiOgnya = 'na-linii-ognya',
  rideToLiveLiveToRide = 'ride-to-live-live-to-ride',
  tanets = 'tanets',
  geniiRoka = 'genii-roka',
  muzikaSfer = 'muzika-sfer',
  pesnyaAnnushki = 'pesnya-annushki',
  smertBerlioza = 'smert-berlioza',
  mechtai = 'mechtai',
  voinaLiveInStudio = 'voina-live-in-studio',
  poTuStoronuSna = 'po-tu-storonu-sna',
  krisi = 'krisi',
  sinKamnya = 'sin-kamnya',
  vremyaVarvarov = 'vremya-varvarov',
  mramorniiAngel = 'mramornii-angel',
  poTuStoronuSna2 = 'po-tu-storonu-sna-2',
  pesniMyortvikh = 'pesni-myortvikh',
  dikieGusi = 'dikie-gusi',
  daiteSvet = 'daite-svet',
  pepelNaVetru = 'pepel-na-vetru',
  nadoelo = 'nadoelo',
  tolkoTiSam = 'tolko-ti-sam',
  yaNeKhochuVoini = 'ya-ne-khochu-voini',
  tatu = 'tatu',
  korablDurakov = 'korabl-durakov',
}
