export const enum EnumArtist {
  id = 'geval',
  name = 'ГЕВАЛ',
}

export const enum EnumAlbums {
  geval = 'geval',
  pergam = 'pergam',
  rim = 'rim',
  longin = 'longin',
  engel = 'engel',
}

export const enum EnumSongs {
  zver = 'zver',
  iuda = 'iuda',
  homoSapiens = 'homo-sapiens',
  kamlanie = 'kamlanie',
  troya = 'troya',
  gryaznyjHleb = 'gryaznyj-hleb',
  quoVadis = 'quo-vadis',
  heruvimy = 'heruvimy',
  geval = 'geval',
  umryomZhivymi = 'umryom-zhivymi',
  pergam = 'pergam',
  vojna = 'vojna',
  armageddon = 'armageddon',
  slepcy = 'slepcy',
  dzhihad = 'dzhihad',
  salomeya = 'salomeya',
  vakhanaliya = 'vakhanaliya',
  epitafiya = 'epitafiya',
  podNatiskom = 'pod-natiskom',
  skulptor = 'skulptor',
  pechatZverya = 'pechat-zverya',
  longin = 'longin',
  harizma = 'harizma',
  tretijRim = 'tretij-rim',
  artefakt = 'artefakt',
  ikar = 'ikar',
  volki = 'volki',
  gotika = 'gotika',
  gorodskojRoman = 'gorodskoj-roman',
  labirint = 'labirint',
  fobosIdejmos = 'fobos-i-dejmos',
  mlechnyjPut = 'mlechnyj-put',
  chyornoBeloe = 'chyorno-beloe',
  skorbyashchijAngel = 'skorbyashchij-angel',
  starikUmorya = 'starik-u-morya',
  sidyashchijDemon = 'sidyashchij-demon',
}
