export const enum EnumArtist {
  id = 'shmely',
  name = 'Шмели',
}

export const enum EnumAlbums {
  trotilovyyeSkazki = 'trotilovyye-skazki',
  tulovishche = 'tulovishche',
  purga = 'purga',
  durackiyeKnizhki = 'durackiye-knizhki',
  petlyaSoblazna = 'petlya-soblazna',
  zloradostnayaOpuhol = 'zloradostnaya-opuhol',
  vulkanizaciyaDushi = 'vulkanizaciya-dushi',
  princessaBezTrusov = 'princessa-bez-trusov',
  bombaVUbezhishche = 'bomba-v-ubezhishche',
  moshchi = 'moshchi',
  trahniNebo = 'trahni-nebo',
  organizm = 'organizm',
  spazmyRoka = 'spazmy-roka',
  risunkiNaDushe = 'risunki-na-dushe',
  poshmelye = 'poshmelye',
  negativProstranstva = 'negativ-prostranstva',
  agressivnyjPokoj = 'agressivnyj-pokoj',
  polnaSuma = 'polna-suma',
  ostanoviteChelovechestvo = 'ostanovite-chelovechestvo',
  zhazhda = 'zhazhda',
  tenSerdca = 'ten-serdca',
  lyod = 'lyod',
  vethijSbornik = 'vethij-sbornik',
  vosemZhenshchinNaRaduge = 'vosem-zhenshchin-na-raduge',
  pugovica = 'pugovica',
  yaVernusKTebe = 'ya-vernus-k-tebe',
  koshkinyObidy = 'koshkiny-obidy',
  karamelnyyeStrahi = 'karamelnyye-strahi',
  moskovskayaYarmarkaUdovolstvij = 'moskovskaya-yarmarka-udovolstvij',
  mekhanicheskayaBalerina = 'mekhanicheskaya-balerina',
  toplivo = 'toplivo',
  cekhPoReabilitaciiParanoikov = 'cekh-po-reabilitacii-paranoikov',
  teatrUrodov = 'teatr-urodov',
  paraTrupov = 'para-trupov',
  belyjKarandash = 'belyj-karandash',
  zloradostnayaOpuholNew = 'zloradostnaya-opuhol-new',
  chudes16 = '16-chudes',
  mizantropiya = 'mizantropiya',
}

export const enum EnumSongs {
  dajGarri = 'daj-garri',
  yaVselennaya = 'ya-vselennaya',
  naLadoniPlaneta = 'na-ladoni-planeta',
  poshmelye = 'poshmelye',
  kakIzydetSvet = 'kak-izydet-svet',
  laboratoriyaAltruizma = 'laboratoriya-altruizma',
}
