export const enum EnumArtist {
  id = 'mc18',
  name = 'ОДИН.ВОСЕМЬ',
}

export const enum EnumAlbums {
  plamya = 'plamya',
  chetyreK = '4k',
  pochtiFantastika = 'pochti-fantastika',
  damaChervi = 'dama-chervi',
  chuzhim = 'chuzhim',
  yad = 'yad',
  akval = 'akval',
  solnce = 'solnce',
  bekdor = 'bekdor',
  kolesnica = 'kolesnica',
  lyudiHaosa = 'lyudi-haosa',
  projtiIostatsya = 'projti-i-ostatsya',
  ubivayaMolodost = 'ubivaya-molodost',
  zaMirIlyubov = 'za-mir-i-lyubov',
}

export const enum EnumSongs {
  zdesIsejchas = 'zdes-i-sejchas',
  pochtiFantastika = 'pochti-fantastika',
  dom = 'dom',
  damaChervi = 'dama-chervi',
  chuzhim = 'chuzhim',
  yad = 'yad',
  akval = 'akval',
  solnce = 'solnce',
  bekdor = 'bekdor',
  odnoSlovo = 'odno-slovo',
  tamKudaIdyom = 'tam-kuda-idyom',
  bezDonorskojKrovi = 'bez-donorskoj-krovi',
  prozhektor = 'prozhektor',
  dokumentalnoeKino = 'dokumentalnoe-kino',
  nikakihOzhidanij = 'nikakih-ozhidanij',
  kajros = 'kajros',
  doVremennojParkovki = 'do-vremennoj-parkovki',
  projtiIostatsya = 'projti-i-ostatsya',
  ubivayaMolodost = 'ubivaya-molodost',
  plamya = 'plamya',
  rikoshet = 'rikoshet',
  ruchej = 'ruchej',
  chetyreKamery = 'chetyre-kamery',
  vBetonnyhBashnyah = 'v-betonnyh-bashnyah',
  sekta = 'sekta',
  lishnij = 'lishnij',
  vmesteSoMnoj = 'vmeste-so-mnoj',
  kolesnica = 'kolesnica',
  absolyut = 'absolyut',
  kakPitDat = 'kak-pit-dat',
  kamen = 'kamen',
  zaMirIlyubov = 'za-mir-i-lyubov',
  tropinka = 'tropinka',
}
