export const enum EnumArtist {
  id = 'tardigrade_inferno',
  name = 'Tardigrade Inferno',
}

export const enum EnumAlbums {
  tardigradeInferno = 'tardigrade-inferno',
  executionIsFun = 'execution-is-fun',
  mastermind = 'mastermind',
  howNightmaresDie = 'how-nightmares-die',
  theWorstOfMe = 'the-worst-of-me',
  spookyScarySkeletons = 'spooky-scary-skeletons',
  arrivalOfATrainSingle = 'arrival-of-a-train-single',
  firePlagueAndLocust = 'fire-plague-and-locust',
  arrivalOfATrain = 'arrival-of-a-train',
  ringmasterHasToDie = 'ringmaster-has-to-die',
  clockworkGod = 'clockwork-god',
  burnTheCircus = 'burn-the-circus',
}

export const enum EnumSongs {
  outOf = '9-out-of-10',
  AGrainOfSand = 'a-grain-of-sand',
  alabamaSong = 'alabama-song',
  allPigsAreTheSame = 'all-pigs-are-the-same',
  allTardigradesGoToHell = 'all-tardigrades-go-to-hell',
  arrivalOfATrain = 'arrival-of-a-train',
  burnTheCircus = 'burn-the-circus',
  cholera = 'cholera',
  churchAsylum = 'church-asylum',
  clockworkGod = 'clockwork-god',
  clownTherapy = 'clown-therapy',
  dreadfulSong = 'dreadful-song',
  engineOfSkin = 'engine-of-skin',
  evoke = 'evoke',
  executionIsFun = 'execution-is-fun',
  firePlagueAndLocust = 'fire-plague-and-locust',
  howNightmaresDie = 'how-nightmares-die',
  hypnosis = 'hypnosis',
  imComingForYourSoul = 'im-coming-for-your-soul',
  littlePrincess = 'little-princess',
  lovelyHost = 'lovely-host',
  marmalade = 'marmalade',
  mastermind = 'mastermind',
  misery = 'misery',
  nailedToTheFerrisWheel = 'nailed-to-the-ferris-wheel',
  rats = 'rats',
  ringmasterHasToDie = 'ringmaster-has-to-die',
  splinterInTheEye = 'splinter-in-the-eye',
  spookyScarySkeletons = 'spooky-scary-skeletons',
  theWorstOfMe = 'the-worst-of-me',
  tickTock = 'tick-tock',
  underwaterValentine = 'underwater-valentine',
  weAreNumberOne = 'we-are-number-one',
  wearingWhite = 'wearing-white',
  writeWithBlood = 'write-with-blood',
}
